[project]
name = "critic-pipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "onnxruntime>=1.21.0",
    "pipecat-ai[cartesia,cartesia,daily,elevenlabs,openai]>=0.0.61",
    "pypdf>=5.4.0",
    "python-dotenv>=1.1.0",
    "tiktoken>=0.9.0",
]
